#<App Name> Service
---
apiVersion: v1
kind: Service
metadata:
  name: <App Name>-service
spec:
  selector:
    app: <App Name>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
  type: LoadBalancer

